notifications:
    slack:
        secure: fMsf7qV6+SL18DQSkAqQX4yRsgiKOw5JpFlMhIRosJH3A8739/9E4feZE7cpBKuOb7/x50/Dd4hjFf7sTGSpqd65U7xDQTEOtEPwAUWMAjoXuJhKjtU1IyXssaEMXHhHF0Advz9ekq/cXIYqbWKcLo9hxnyZS8YAHBL/r5Cjm0/aIvmcvFnlcZCq2FG2MUaGm/wG8bSrJ84eCwIcN3lu1UD6/Z3Y3btmXE0/HGCRbWTsfIjn1F+xrfK/GCxr01vLsZGRm3ADRi+2rhOemPmgM0hGa9IiStzIKPVh0rN2M6gSFgczrYLJbrwujUCx+KgRJt+kR4D0J7rMxYGQIAA655nilXhzFxknwY4f8cRszJfEJe60oFOh4BruDR+d0IjO2DgLWhebqQS05lUlXV2L5GDTogxrl40nw661V7HewNLYFcykAKg4W1QXiaqhK+06pweRaTDPmqIHDJa2sUMupb8W3AMqOrBPX2wY73PCZGZzabesKeyk0oL6HOEgCdEH1m/uri92tNPX/GfWKQl0zgBBZmOyf8UcIWDQWtVPVuOwUi9dhn5/8SoQ2GKld9vlh3G8aDCwxjlW3NVJ67kv8v6fMV3qGZWqLQorDVwGLhlUsyApI0HR6QXCJHVmOBk3HP6wWvztJi6oJF88extJ0AAWTExD1zXUbMT/MfQJvQQ=

git:
    depth: 1
    quiet: true
    submodules: false

install: true

branches:
    only:
        - master

language: go
go_import_path: github.com/mkenney/go-chrome
go:
    - 1.11.x
    - tip

ignore:
    - "cmd/.*"
    - "test/.*"
    - "pkg/vendor/.*"

script:
    - ./.travis.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
