# Service
kind: Service
apiVersion: v1
metadata:
    name: k8s-proxy
spec:
    selector:
        app: k8s-proxy
    type: LoadBalancer
    ports:
        -   port: 80
            targetPort: 80
            protocol: TCP
            name: k8s-proxy
        -   port: 443
            targetPort: 443
            protocol: TCP
            name: k8s-proxy-ssl
---
# Deployment
kind: Deployment
apiVersion: apps/v1beta1
metadata:
    name: k8s-proxy
    labels:
        app: k8s-proxy
spec:
    replicas: 1
    revisionHistoryLimit: 2
    strategy:
        rollingUpdate:
            maxSurge: 3
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            name: k8s-proxy
            labels:
                app: k8s-proxy
        spec:
            containers:
                -   name: k8s-proxy
                    image: k8s-proxy
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 80
                            #name: k8s-proxy
                        -   containerPort: 443
                            #name: k8s-proxy-ssl
                    env:
                        -   name: LOG_LEVEL
                            value: debug
                        -   name: DEFAULT_SERVICE
                            value: "kubernetes"
                        -   name: DEV
                            value: "true"
                        -   name: LIVENESS_PROBE
                            value: "true"
                        -   name: READINESS_PROBE
                            value: "true"
                        -   name: PORT
                            value: "80"
                        -   name: SECUREPORT
                            value: "443"
                        -   name: TIMEOUT
                            value: "10"

                    resources:
                        limits:
                            cpu: 2
                            memory: 2Gi
                        requests:
                            cpu: 0.1
                            memory: 128Mi
                    #livenessProbe:
                    #    httpGet:
                    #        path: "/alive"
                    #        port: 80
                    #        scheme: HTTP
                    #    failureThreshold: 3
                    #    initialDelaySeconds: 10
                    #    periodSeconds: 10
                    #    timeoutSeconds: 5
                    #readinessProbe:
                    #    httpGet:
                    #        path: "/ready"
                    #        port: 80
                    #        scheme: HTTP
                    #    failureThreshold: 3
                    #    initialDelaySeconds: 10
                    #    periodSeconds: 10
                    #    timeoutSeconds: 5
                    volumeMounts:
                        -   mountPath: /go/bin
                            name: binpath
            volumes:
                -   name: binpath
                    hostPath:
                        path: /Users/mkenney/repos/src/github.com/mkenney/k8s-proxy/bin
