
[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/mkenney/go-log-fmt"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v6.0.0"
